#!/bin/sh
#
# Build the vt-ferry guest runtime container image and push it
# to a local Docker registry so smolvm can pull it. The image
# carries the patched Linux FFmpeg, the guest shim shared library,
# the libCore* / libVideoToolbox symlinks, and the shim headers
# under /opt/vt-ferry/. Distro `ffmpeg` is also installed at
# /usr/bin/ffmpeg so smokes can run the libavcodec software
# baseline through the standard path.
#
# Why a local registry: smolvm pulls images from a registry; it
# can't load a local-only Docker image directly. We start a
# registry container on localhost:5005, push the built image there,
# and tell the caller (or env.sh) to set
# VM_IMAGE=localhost:5005/vt-ferry-guest:<tag>.
#
# Usage:
#   ffmpeg/scripts/build_vt_ferry_image.sh
#   FFMPEG_REF=n8.1 IMAGE_TAG=dev ffmpeg/scripts/build_vt_ferry_image.sh
#
# After a successful build, source the printed env.sh path to
# pick up VM_IMAGE for subsequent smoke runs:
#   . artifacts/vt-ferry-guest-image/env.sh
#   sh ffmpeg/scripts/prove_smolvm_videotoolbox_encode.sh

set -eu

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname "$0")" && pwd)"
REPO_ROOT="$(CDPATH= cd -- "${SCRIPT_DIR}/../.." && pwd)"

FFMPEG_REF="${FFMPEG_REF:-n8.1}"
IMAGE_NAME="${IMAGE_NAME:-vt-ferry-guest}"
IMAGE_TAG="${IMAGE_TAG:-dev}"
REGISTRY_NAME="${REGISTRY_NAME:-vt-ferry-registry}"
REGISTRY_PORT="${REGISTRY_PORT:-5005}"
PLATFORM="${PLATFORM:-linux/arm64}"
OUT_DIR="${OUT_DIR:-${REPO_ROOT}/artifacts/vt-ferry-guest-image}"

die() {
  echo "ERROR: $*" >&2
  exit 1
}

command -v docker >/dev/null 2>&1 || die "docker is required (install Docker Desktop or a docker daemon)"
docker info >/dev/null 2>&1 || die "docker is installed but the daemon is not reachable"

mkdir -p "${OUT_DIR}"
local_tag="${IMAGE_NAME}:${IMAGE_TAG}"
registry_image="localhost:${REGISTRY_PORT}/${IMAGE_NAME}:${IMAGE_TAG}"

echo "==> Ensuring local registry container is running on :${REGISTRY_PORT}"
if [ -z "$(docker ps --filter "name=${REGISTRY_NAME}" --format '{{.Names}}')" ]; then
  if [ -n "$(docker ps -a --filter "name=${REGISTRY_NAME}" --format '{{.Names}}')" ]; then
    docker start "${REGISTRY_NAME}" >/dev/null
  else
    docker run -d \
      --name "${REGISTRY_NAME}" \
      --restart=unless-stopped \
      -p "${REGISTRY_PORT}:5000" \
      registry:2 >/dev/null
  fi
fi

echo "==> Building image ${local_tag} (FFMPEG_REF=${FFMPEG_REF})"
docker build \
  --platform="${PLATFORM}" \
  --build-arg "FFMPEG_REF=${FFMPEG_REF}" \
  -f "${REPO_ROOT}/ffmpeg/Dockerfile" \
  -t "${local_tag}" \
  "${REPO_ROOT}"

echo "==> Tagging + pushing ${registry_image}"
docker tag "${local_tag}" "${registry_image}"
docker push "${registry_image}" >/dev/null

cat >"${OUT_DIR}/env.sh" <<EOF
# Generated by ffmpeg/scripts/build_vt_ferry_image.sh
# Source this before vt-ferry smokes / gates / benchmarks to use
# the prebuilt vt-ferry guest image.
export VM_IMAGE="${registry_image}"
# The image already has /opt/vt-ferry/bin/ffmpeg, so smokes can
# skip the bind-mounted host artifact path.
export GUEST_FFMPEG_BIN="/opt/vt-ferry/bin/ffmpeg"
# The shim libs live in /opt/vt-ferry/lib/ inside the image and
# are picked up by ldconfig — no LD_LIBRARY_PATH needed.
export GUEST_SHIM_LIBDIR=""
# Skip the per-smoke shim rebuild + stage step; the image already
# carries the shim.
export STAGE_SHIM_LIBS=0
EOF

cat <<EOF

==> Built vt-ferry guest image:
  ${registry_image}

To use with the smokes:
  . ${OUT_DIR}/env.sh
  sh ffmpeg/scripts/prove_smolvm_videotoolbox_encode.sh

The local registry container is:
  ${REGISTRY_NAME}  (Docker container, listening on :${REGISTRY_PORT})

EOF
