#!/bin/sh
#
# 4K variant of v1_decode_perf_gate.sh.
#
# At 4K the per-frame NV12 size is 12,441,600 bytes (~11.9 MiB) —
# four times the 1080p budget. The pool path takes ~12 chunked
# OP_READ_BUFFER round trips per frame, so transport CPU and
# wallclock both grow proportionally to frame area. The gate
# thresholds here reflect that:
#
#   * MAX_GUEST_VS_HOST_DECODE_RATIO   4.0   (loosened from 1080p's
#                                             2.5 — host VT decode
#                                             at 4K stays fast (ANE)
#                                             so the host wallclock
#                                             stays sub-second, but
#                                             guest pays full 12
#                                             MiB/frame NV12 transit
#                                             across vsock. Observed
#                                             ~2.88x post-Phase-15)
#   * MIN_GUEST_DECODE_REALTIME        1.0   (loosened from 1080p's
#                                             5.0 — 4K30 is ~120 MB/s
#                                             of raw NV12, transport
#                                             dominates at this size)
#   * MAX_GUEST_DECODE_CPU_RATIO       2.0   (loosened from 1080p's
#                                             1.5 — same reasoning,
#                                             transport CPU is ~4×
#                                             larger and there's no
#                                             compressed-output lever
#                                             on the decode side)
#
# Defaults:
#   * REFERENCE_VIDEO  synthetic 4K clip generated by the README
#                      in artifacts/reference-videos/
#   * FRAME_LIMIT      60 (2 seconds of 4K source — matches the
#                      4K encode gate)
#
# Usage:
#   ffmpeg/scripts/v1_decode_perf_gate_4k.sh
#   FRAME_LIMIT=120 ffmpeg/scripts/v1_decode_perf_gate_4k.sh

set -eu

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname "$0")" && pwd)"
REPO_ROOT="$(CDPATH= cd -- "${SCRIPT_DIR}/../.." && pwd)"

REFERENCE_VIDEO="${REFERENCE_VIDEO:-${REPO_ROOT}/artifacts/reference-videos/synthetic_4k_30fps_5s.mp4}"
FRAME_LIMIT="${FRAME_LIMIT:-60}"
MAX_GUEST_VS_HOST_DECODE_RATIO="${MAX_GUEST_VS_HOST_DECODE_RATIO:-4.0}"
MIN_GUEST_DECODE_REALTIME="${MIN_GUEST_DECODE_REALTIME:-1.0}"
MAX_GUEST_DECODE_CPU_RATIO="${MAX_GUEST_DECODE_CPU_RATIO:-2.0}"

if [ ! -f "${REFERENCE_VIDEO}" ]; then
    echo "ERROR: REFERENCE_VIDEO not found: ${REFERENCE_VIDEO}" >&2
    echo "" >&2
    echo "Generate the synthetic 4K clip with:" >&2
    echo "  ffmpeg -y -f lavfi -i testsrc2=size=3840x2160:rate=30:duration=5 \\" >&2
    echo "         -c:v libx264 -preset ultrafast -pix_fmt yuv420p \\" >&2
    echo "         artifacts/reference-videos/synthetic_4k_30fps_5s.mp4" >&2
    echo "or set REFERENCE_VIDEO=/path/to/4k_clip.mp4." >&2
    exit 1
fi

REFERENCE_VIDEO="${REFERENCE_VIDEO}" \
FRAME_LIMIT="${FRAME_LIMIT}" \
MAX_GUEST_VS_HOST_DECODE_RATIO="${MAX_GUEST_VS_HOST_DECODE_RATIO}" \
MIN_GUEST_DECODE_REALTIME="${MIN_GUEST_DECODE_REALTIME}" \
MAX_GUEST_DECODE_CPU_RATIO="${MAX_GUEST_DECODE_CPU_RATIO}" \
exec "${SCRIPT_DIR}/v1_decode_perf_gate.sh" "$@"
