#!/bin/sh
#
# 4K variant of v1_perf_gate.sh.
#
# 4K H.264 encode is materially harder than 1080p — guest libx264
# drops to ~1.09x realtime, and even host libx264 only manages
# ~2.24x. Hardware VideoToolbox is the only path that comfortably
# stays above realtime in the guest. The thresholds here reflect
# that, with floors loosened from the 1080p gate but the CPU-
# efficiency cap kept the same (the value-of-hardware story is
# even sharper at 4K).
#
# Defaults:
#   * REFERENCE_VIDEO          synthetic 4K clip generated by the
#                              README in artifacts/reference-videos/
#   * FRAME_LIMIT              60 (2 seconds of 4K source)
#   * MIN_GUEST_VT_REALTIME    1.0 (must keep up with realtime;
#                              baseline observed ≈ 1.67x)
#   * MAX_GUEST_VS_HOST_VT_RATIO  2.0 (same as 1080p)
#   * MAX_GUEST_VT_CPU_RATIO   0.5 (same as 1080p; baseline ≈ 0.18)

set -eu

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname "$0")" && pwd)"
REPO_ROOT="$(CDPATH= cd -- "${SCRIPT_DIR}/../.." && pwd)"

REFERENCE_VIDEO="${REFERENCE_VIDEO:-${REPO_ROOT}/artifacts/reference-videos/synthetic_4k_30fps_5s.mp4}"
FRAME_LIMIT="${FRAME_LIMIT:-60}"
MIN_GUEST_VT_REALTIME="${MIN_GUEST_VT_REALTIME:-1.0}"
MAX_GUEST_VS_HOST_VT_RATIO="${MAX_GUEST_VS_HOST_VT_RATIO:-2.0}"
MAX_GUEST_VT_CPU_RATIO="${MAX_GUEST_VT_CPU_RATIO:-0.5}"

if [ ! -f "${REFERENCE_VIDEO}" ]; then
    echo "ERROR: REFERENCE_VIDEO not found: ${REFERENCE_VIDEO}" >&2
    echo "" >&2
    echo "Generate the synthetic 4K clip with:" >&2
    echo "  ffmpeg -y -f lavfi -i testsrc2=size=3840x2160:rate=30:duration=5 \\" >&2
    echo "         -c:v libx264 -preset ultrafast -pix_fmt yuv420p \\" >&2
    echo "         artifacts/reference-videos/synthetic_4k_30fps_5s.mp4" >&2
    echo "or set REFERENCE_VIDEO=/path/to/4k_clip.mp4." >&2
    exit 1
fi

REFERENCE_VIDEO="${REFERENCE_VIDEO}" \
FRAME_LIMIT="${FRAME_LIMIT}" \
MIN_GUEST_VT_REALTIME="${MIN_GUEST_VT_REALTIME}" \
MAX_GUEST_VS_HOST_VT_RATIO="${MAX_GUEST_VS_HOST_VT_RATIO}" \
MAX_GUEST_VT_CPU_RATIO="${MAX_GUEST_VT_CPU_RATIO}" \
exec "${SCRIPT_DIR}/v1_perf_gate.sh" "$@"
